# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
services: docker
sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - PKG_CONFIG_ALLOW_CROSS=1
    - CRATE_NAME=rust-igmc-2018
  matrix:
    - TARGET=i686-unknown-linux-gnu
    - TARGET=x86_64-unknown-linux-gnu
    - TARGET=i686-pc-windows-gnu
    - TARGET=x86_64-pc-windows-gnu

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true

before_cache:
  - chmod -R a+r $HOME/.cargo
cache: cargo

addons:
  apt:
    update: true
    packages:
      - pkg-config
      - build-essential
      - cmake
      - libasound2-dev
      - libsdl2-dev
      - libx11-xcb-dev
      - libssl-dev
      - libfreetype6-dev
      - libexpat1-dev
      - libxcb1-dev

before_install:
  - |
      if [ ${TRAVIS_OS_NAME} == "windows" ]
      then
        wget --no-check-certificate https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
        7z x SDL2-devel-2.0.8-VC.zip
        cp SDL2-2.0.8/lib/x64/*.lib ${HOME}/.rustup/toolchains/${TRAVIS_RUST_VERSION}-x86_64-pc-windows-msvc/lib/rustlib/x86_64-pc-windows-msvc/lib
        cp SDL2-2.0.8/lib/x64/*.dll .
        rm SDL2-devel-2.0.8-VC.zip
      fi
  - set -e
  - rustup self update

script:
  - cargo build --verbose --all --target $TARGET
  - cargo build --verbose --all --target $TARGET --release
  - cargo test --verbose --all --target $TARGET
  - cargo test --verbose --all --target $TARGET --release
  - cargo run --verbose --bin nk_tool --target $TARGET
  - cargo run --verbose --bin nk_tool --target $TARGET --release

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "Vt4wqZ8n0cQqYXmxE+2FKEN6ZXdw9FZ/D+MYnJii17mF1G0lBGlw8Gl0C3Wf77arNIbQ9YYP6dxn/DyCAOMUCTT5y3sbdwJX3mBwLAFHtezM8VRMrIrTOaDBZ7h6mLuOeAc0rJ4SlFUtMzEl2zwaIoLctSrq9UV5ev7R43q6XaC1kLH/0cny2dG4xu+IgdlWpigxcK/ZuffjK+ZV/jy4Ly5KRiiwYNBY09vyhZfodMPCu9ekuaFGPHuRyeACwvLTusXHJjHUt4i2VJPO9tfsZ8tzzvxJDBsnNQfM+E48nRE+6jGIWq3BBMuZ4Pp7tN4aKUvWqgW0Sy9bPon8du6BbZX+j5LKFeOGhwuY5fsf+VMxpVkgLQla4jp/EUvx+/58aSBgcF6A5ng0gaunM8YbCq5DGs96T2qY8U3mRB1Sl3b9SgUk+M/OI688xZ5yzUIhgeFTQ3Ad8Jwnx40ZDBhBLCe1HqosBKxSLQ7oUGC9r1JsqfiieTNTD/ljP5oTt5GXLtRQ8OrMDKHsdHA0EJLaLr5VbKpy/odb4X/QxCUSNs0Ahs6hKLBAYRKLfbfFrjkCaewQu7UhKaB7dYs8s2r8YpmR2glzTWdoRXzlxPYS5YOqaTOvWP9JZhCi7wTlZKOcWkOL1Qs1J87IJm0EVC2KPu/UtwAT248LKTbTTCZyS3s="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
